"""Assemble polished Tripo pieces, add original art and naturally loose cables.
blender -b -P scripts/models/blender/bedroom_tv_tripo_assemble.py -- SOURCE_ROOT DEST_GLB RENDER_DIR
All shelf/hardware/controller/case geometry is imported from the recorded Tripo jobs.
"""
import bpy,bmesh,sys,os,math,json
from mathutils import Vector,Matrix
from mathutils.bvhtree import BVHTree
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from bedroom_tv_common import *
SRC,DST,RENDER=[os.path.abspath(x) for x in sys.argv[sys.argv.index('--')+1:]]
bpy.ops.wm.read_factory_settings(use_empty=True)
for key,c,r,m in [('rubber',0x181a21,.65,0),('silver',0xbec2c8,.49,.08),('chrome',0xc7ccd2,.28,.8),
                  ('graphite',0x34353a,.49,.02),('black',0x20222a,.5,0),('grey',0xa6aab3,.48,0),('white',0xdadbd8,.45,0),
                  ('red',0xbc3247,.4,0),('yellow',0xe5ba4d,.4,0),('green',0x3aaa85,.4,0),('gold',0xb8a575,.4,.2)]:
    MAT[key]=material('bedroom-'+key,c,r,m)
image_mat('covers','.source-assets/bedroom-tv/covers.png')
image_mat('bedroom-spines',os.path.join(SRC,'print','spines.png'))
image_mat('bedroom-badges',os.path.join(SRC,'print','badges.png'))
image_mat('crt-image','.source-assets/bedroom-tv/melee-Named_Snaps.png',.75)
image_mat('gb-image','.source-assets/bedroom-tv/links-awakening-Named_Snaps.png',.05)
image_mat('ds-top-image','.source-assets/bedroom-tv/ds-top.png',.28)
image_mat('ds-touch-image','.source-assets/bedroom-tv/ds-touch.png',.28)
pieces=[];provenance=[]

def load(name,outname):
    before=set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=os.path.join(SRC,'polished',name+'.glb'),merge_vertices=True)
    new=[o for o in bpy.data.objects if o not in before and o.type=='MESH']
    select_only(new[0])
    for o in new:o.select_set(True)
    if len(new)>1:bpy.ops.object.join()
    o=bpy.context.object
    bpy.ops.object.parent_clear(type='CLEAR_KEEP_TRANSFORM');bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    o.name=outname
    o.rotation_mode='XYZ'
    if name in ['melee-case','gamecube-stack','snes-cartridge','n64-cartridge']:
        o.data.materials.clear();o.data.materials.append(MAT['black' if name in ['melee-case','gamecube-stack']else 'grey'])
    # Canonical source coordinates: centre X/Y, lower edge Z=0, as generated by Tripo.
    bb=[Vector(c) for c in o.bound_box];lo=Vector([min(p[i] for p in bb)for i in range(3)]);hi=Vector([max(p[i]for p in bb)for i in range(3)])
    for v in o.data.vertices:v.co.z-=lo.z
    o.data.update()
    o['tripoReference']=name;pieces.append(o);provenance.append({'assembly':outname,'source':name})
    return o,hi-lo

def tree(o):
    return BVHTree.FromPolygons([v.co for v in o.data.vertices],[p.vertices for p in o.data.polygons],all_triangles=False)

def patch(o,name,x0,x1,a0,a1,mat,tile=None,axis='front',row=None,rows=8,nx=16,ny=12):
    # Ray-conformed printing follows the real generated glass/case rather than floating as a rectangle.
    bvh=tree(o);verts=[];uv=[];faces=[]
    for j in range(ny+1):
        v=j/ny;a=a0+(a1-a0)*v
        for i in range(nx+1):
            u=i/nx;x=x0+(x1-x0)*u
            origin=Vector((x,-2,a)) if axis=='front' else Vector((x,a,2))
            direction=Vector((0,1,0)) if axis=='front' else Vector((0,0,-1))
            hit,n,_,_=bvh.ray_cast(origin,direction)
            if hit is None:raise RuntimeError(f'{o.name}/{name}: printing missed source surface at {tuple(origin)}')
            hit-=direction*.0018
            verts.append(tuple(hit))
            if tile is not None:
                col,r=tile%4,tile//4;uv.append(((col+.006+u*.988)/4,(1-r*.5)-.004-(1-v)*.492))
            elif row is not None:uv.append((u,(rows-1-row+v)/rows))
            else:uv.append((u,v))
    for j in range(ny):
        for i in range(nx):
            a=j*(nx+1)+i
            faces.append((a,a+1,a+nx+2,a+nx+1))
    p=mesh(name,verts,faces,mat,uv)
    for f in p.data.polygons:f.use_smooth=True
    p.parent=o;pieces.append(p)
    return p

def place(o,dims,x,y,base,angle=0,rx=0):
    # Resize once to the real object, then let the lower world bound rest on its shelf.
    bb=[Vector(c)for c in o.bound_box];size=Vector([max(p[i]for p in bb)-min(p[i]for p in bb)for i in range(3)])
    o.scale=tuple(dims[i]/size[i]for i in range(3))
    o.rotation_euler=(math.radians(rx),0,math.radians(angle))
    o.location=(x,y,0);bpy.context.view_layer.update()
    low=min((o.matrix_world@v.co).z for v in o.data.vertices)
    o.location.z=base-low;bpy.context.view_layer.update()

stand,_=load('stand','tv-stand');place(stand,(1.18,.50,.75),0,0,.012)
standtree=BVHTree.FromPolygons([stand.matrix_world@v.co for v in stand.data.vertices],[p.vertices for p in stand.data.polygons],all_triangles=True)
def shelf(x,y,level):
    start={2:1,1:.65,0:.30}[level]
    hit,*_=standtree.ray_cast(Vector((x,y,start)),Vector((0,0,-1)))
    if hit is None:raise RuntimeError('Shelf ray missed')
    return hit.z+.0015
levels=[shelf(0,0,i)for i in range(3)];print('SHELF_LEVELS',levels,flush=True)

crt,_=load('crt','bedroom-crt')
bm=bmesh.new();bm.from_mesh(crt.data)
# Retopologize the damaged face while preserving Tripo's deep shell and its curved tube.
remove=[]
for f in bm.faces:
    c=f.calc_center_median()
    glass=abs(c.x)<.381 and .188<c.z<.690
    if c.y<-.390 and not glass:remove.append(f)
bmesh.ops.delete(bm,geom=remove,context='FACES');bm.to_mesh(crt.data);bm.free()
screen=patch(crt,'crt-screen',-.369,.369,.210,.675,'crt-image',nx=32,ny=24)
print('CRT_SURFACE',list(screen.data.vertices[len(screen.data.vertices)//2].co),flush=True)
before=set(bpy.data.objects)
def ring_loop(w,h,r,y,z):return [(x,y,z+a)for x,a in rounded_loop(w,h,r)]
outer=ring_loop(.976,.792,.036,-.435,.400)
inner=ring_loop(.772,.511,.014,-.443,.441)
N=len(outer);faces=[(i,(i+1)%N,(i+1)%N+N,i+N)for i in range(N)]
mesh('crt-bezel-surface-repaired',outer+inner,faces,'silver')
loft('crt-bezel-outer-roll',[ring_loop(.976,.792,.036,-.435,.400),ring_loop(.969,.784,.038,-.413,.400),ring_loop(.959,.775,.038,-.380,.400)],'silver',caps=False)
inside=ring_loop(.758,.497,.012,-.441,.441)
mesh('crt-glass-surround-repaired',inner+inside,faces,'black')
# Repair the small chin details after flattening its noisy generated front surface.
for cx in [-.306,.306]:
    rb('crt-speaker-grille',cx-.091,cx+.091,-.453,-.438,.061,.132,'silver',.007,.001,axis=1)
    for col in range(14):
        for row in range(6):disk('crt-grille-perforation',cx+(col-6.5)*.0118,-.4542,.069+row*.011,.00175,.0012,'black',axis='Y',verts=8)
disk('crt-power-key',-.167,-.455,.096,.013,.006,'silver',axis='Y',verts=32)
disk('crt-status-light',-.142,-.455,.096,.0024,.001,'green',axis='Y',verts=16)
for i in range(5):disk('crt-menu-key',-.092+i*.036,-.455,.082,.0058,.004,'silver',axis='Y',verts=24)
text('crt-brand-restored','SONY',0,-.456,.140,.021,'black')
rb('crt-av-sockets',.139,.229,-.453,-.438,.076,.115,'black',.006,.001,axis=1)
for i,key in enumerate(['yellow','white','red']):
    disk('crt-port-metal',.156+i*.028,-.455,.096,.009,.004,'chrome',axis='Y',verts=24)
    disk('crt-port-colour',.156+i*.028,-.458,.096,.0062,.003,key,axis='Y',verts=24)
for p in [o for o in bpy.data.objects if o not in before and o.type=='MESH']:p.parent=crt;pieces.append(p)
place(crt,(.55,.49,.447),-.19,-.005,shelf(-.19,0,2),angle=-1.5)

gc,_=load('gamecube','nintendo-gamecube')
bm=bmesh.new();bm.from_mesh(gc.data);remove=[]
for f in bm.faces:
    c=f.calc_center_median()
    front=all(v.co.y<-.446 and abs(v.co.x)<.405 and .070<v.co.z<.490 for v in f.verts)
    lid=all(v.co.x*v.co.x+v.co.y*v.co.y<.281**2 and v.co.z>.540 for v in f.verts)
    if front or lid:remove.append(f)
bmesh.ops.delete(bm,geom=remove,context='FACES');bm.to_mesh(gc.data);bm.free()
before=set(bpy.data.objects)
plate=rb('gamecube-front-panel-repaired',-.404,.404,-.495,-.447,.079,.477,'silver',.013,.003,axis=1)
for cx in [-.273,-.091,.091,.273]:
    cutter=cyl('port-cut',.049,cx,.327,-.495,-.432,'black',verts=32)
    boolean(plate,cutter)
    disk('controller-port-recess',cx,-.454,.327,.047,.005,'black',axis='Y',verts=32)
    disk('controller-port-insert',cx,-.460,.327,.020,.009,'darkgrey' if 'darkgrey' in MAT else 'black',axis='Y',verts=16)
for cx in [-.190,.190]:
    cutter=rb('memory-cut',cx-.114,cx+.114,-.498,-.433,.164,.195,'black',.004,.001,axis=1)
    boolean(plate,cutter)
    rb('memory-port-interior',cx-.112,cx+.112,-.451,-.447,.166,.193,'black',.003,.0005,axis=1)
lid=disk('gamecube-disc-lid-repaired',0,0,.578,.287,.012,'silver',verts=96)
for p in [o for o in bpy.data.objects if o not in before and o.type=='MESH']:p.parent=gc;pieces.append(p)
patch(lid,'gamecube-disc-print',-.122,.122,-.038,.041,'bedroom-badges',row=1,rows=4,axis='top',ny=4)
place(gc,(.21,.21,.145),-.36,.067,shelf(-.36,.067,1),angle=3)
snes,_=load('snes','nintendo-snes');place(snes,(.30,.244,.085),-.31,.052,shelf(-.31,.052,0),angle=-4)
n64,_=load('n64','nintendo-64');place(n64,(.265,.207,.077),.285,.027,shelf(.285,.027,0),angle=5)

gb,_=load('gameboy','nintendo-gameboy')
patch(gb,'gameboy-lcd',-.179,.179,.583,.815,'gb-image')
place(gb,(.09,.032,.146),.462,.128,shelf(.462,.128,2),angle=-12,rx=-66)
ds,_=load('ds','nintendo-ds')
patch(ds,'ds-upper-screen',-.212,.212,.277,.587,'ds-top-image')
patch(ds,'ds-touch-screen',-.216,.216,-.214,.105,'ds-touch-image',axis='top')
place(ds,(.147,.106,.104),.29,.035,shelf(.29,.035,2),angle=8)

for src,name,dim,x,y,level,angle in [
 ('gamecube-controller','gamecube-controller',(.155,.039,.114),.277,-.130,1,-16),
 ('snes-controller','snes-controller',(.145,.027,.066),-.30,-.178,0,13),
 ('n64-controller','n64-controller',(.169,.044,.134),.293,-.179,0,-12)]:
    o,_=load(src,name);place(o,dim,x,y,shelf(x,y,level),angle=angle,rx=-58 if src=='gamecube-controller' else -62)

stack,_=load('gamecube-stack','bedroom-gamecube-stack')
for row,z in enumerate([.041,.117,.190,.264,.339,.413,.490]):
    patch(stack,'gamecube-spine-'+str(row),-.392,.380,z-.021,z+.021,'bedroom-spines',row=row,nx=16,ny=2)
patch(stack,'top-game-cover',-.420,.402,-.300,.315,'covers',tile=1,axis='top')
place(stack,(.195,.15,.104),.272,.045,shelf(.272,.045,1),angle=-7)
other=stack.copy();other.data=stack.data.copy();other.name='bedroom-gamecube-stack-second';bpy.context.collection.objects.link(other)
for child in list(stack.children):
    copy=child.copy();copy.data=child.data.copy();bpy.context.collection.objects.link(copy);copy.parent=other;pieces.append(copy)
pieces.append(other);other.location.x=-.072;other.location.y=.125;other.rotation_euler.z=math.radians(5)
other.scale*=.85;other.location.z=shelf(-.072,.125,1);bpy.context.view_layer.update()

case,_=load('melee-case','bedroom-melee-case')
patch(case,'melee-original-cover',-.323,.323,.029,.952,'covers',tile=0)
place(case,(.13,.013,.185),-.117,-.142,shelf(-.117,-.142,1),angle=5)
zelda,_=load('melee-case','bedroom-wind-waker-case')
patch(zelda,'wind-waker-original-cover',-.323,.323,.029,.952,'covers',tile=1)
place(zelda,(.129,.013,.184),.045,-.074,shelf(.045,-.074,1),angle=-13)

retro,_=load('retro-games','bedroom-retro-games')
patch(retro,'retro-upper-zelda-box',-.40,.14,.015,.36,'covers',tile=5,axis='top')
patch(retro,'retro-yoshi-cartridge',-.34,-.21,-.26,-.13,'covers',tile=3,axis='top')
place(retro,(.235,.223,.064),-.032,.062,shelf(-.032,.062,0),angle=-8)

for src,name,tile,x,y,base,angle in [
 ('snes-cartridge','bedroom-yoshi-cartridge',3,-.31,.105,levels[0]+.055,-4),
 ('n64-cartridge','bedroom-smash64-cartridge',4,.279,.081,levels[0]+.057,5),
 ('n64-cartridge','bedroom-ocarina-cartridge',2,.066,-.140,levels[0]+.002,-11),
 ('snes-cartridge','bedroom-link-past-cartridge',5,-.083,-.132,levels[0]+.002,9)]:
    o,d=load(src,name)
    patch(o,name+'-label',-.334,.334,.253,.550,'covers',tile=tile)
    if 'ocarina' in name:
        o.data.materials[0]=o.data.materials[0].copy();o.data.materials[0].name='bedroom-ocarina-gold'
        for m in o.data.materials:
            # Gold cartridge finish keeps its real generated shape.
            m.diffuse_color=(.55,.46,.24,1)
            p=m.node_tree.nodes.get('Principled BSDF')
            for link in list(m.node_tree.links):
                if link.to_socket==p.inputs['Base Color']:m.node_tree.links.remove(link)
            p.inputs['Base Color'].default_value=(.55,.46,.24,1)
    place(o,(.112,.023,.078),x,y,base,angle=angle)

for name,tile,x,y,angle in [('bedroom-links-awakening-box',6,.30,.135,8),('bedroom-mario-ds-case',7,.13,.130,-9)]:
    o,_=load('melee-case',name)
    patch(o,name+'-art',-.323,.323,.029,.952,'covers',tile=tile)
    place(o,(.082,.018,.095),x,y,shelf(x,y,2),angle=angle,rx=-90)

before=set(bpy.data.objects)
wire('gamecube-cable',[(-.439,-.040,levels[1]+.085),(-.49,-.14,levels[1]+.043),(-.34,-.23,levels[1]+.004),(-.06,-.208,levels[1]+.003),(.18,-.135,levels[1]+.012),(.275,-.115,levels[1]+.034)],.0018)
wire('snes-cable',[(-.389,-.073,levels[0]+.038),(-.44,-.14,levels[0]+.015),(-.42,-.20,levels[0]+.003),(-.32,-.225,levels[0]+.003),(-.26,-.17,levels[0]+.016),(-.30,-.145,levels[0]+.03)],.0015)
wire('n64-cable',[(.183,-.077,levels[0]+.028),(.11,-.18,levels[0]+.005),(.15,-.23,levels[0]+.003),(.37,-.223,levels[0]+.003),(.395,-.15,levels[0]+.007),(.29,-.11,levels[0]+.034)],.0018)
wire('tv-power',[(-.19,.231,.93),(-.24,.262,.66),(-.26,.264,.22),(-.43,.23,.029),(-.63,.19,.018)],.003)
wire('cube-av',[(-.36,.176,levels[1]+.069),(-.40,.26,levels[1]),(-.43,.265,.58),(-.10,.252,.76)],.0022)
wire('av-to-tv',[(-.08,-.215,.802),(-.04,-.264,.77),(.01,-.17,.755),(.08,.16,.753),(-.10,.252,.76)],.002)
for i,key in enumerate(['yellow','white','red']):
    pos=crt.matrix_world@Vector((.156+i*.028,-.462,.096))
    disk('crt-av-plug',pos.x,pos.y-.003,pos.z,.0032,.012,key,axis='Y',verts=20)
    wire('crt-av-tail',[(pos.x,pos.y-.009,pos.z),(pos.x+.013,-.263,.787),(-.04,-.264,.77)],.0013)
group_piece('bedroom-cables',before);pieces.extend([o for o in bpy.data.objects if o not in before and o.type=='MESH'])

# Bind child printing to the same world transform, keeping names usable by the runtime batching pass.
for o in pieces:
    select_only(o);bpy.ops.object.parent_clear(type='CLEAR_KEEP_TRANSFORM')
    bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    tri=o.modifiers.new('triangles','TRIANGULATE');bpy.ops.object.modifier_apply(modifier=tri.name)
os.makedirs(os.path.dirname(DST),exist_ok=True)
for o in bpy.context.selected_objects:o.select_set(False)
for o in pieces:o.select_set(True)
bpy.ops.export_scene.gltf(filepath=DST,export_format='GLB',use_selection=True,export_apply=True,export_yup=True,export_image_format='WEBP',export_image_quality=91)
os.makedirs(RENDER,exist_ok=True)
with open(os.path.join(RENDER,'assembly.json'),'w')as f:json.dump({'triangles':sum(len(o.data.polygons)for o in pieces),'sources':provenance,'shelves':levels},f,indent=2)
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=48;scene.cycles.use_denoising=True;scene.cycles.device='GPU'
prefs=bpy.context.preferences.addons['cycles'].preferences;prefs.compute_device_type='OPTIX';prefs.get_devices()
for d in prefs.devices:d.use=d.type!='CPU'
scene.render.resolution_x=1600;scene.render.resolution_y=1600;scene.render.resolution_percentage=100
scene.world=bpy.data.worlds.new('bedroom studio');scene.world.use_nodes=True
scene.world.node_tree.nodes['Background'].inputs[0].default_value=(.11,.12,.16,1)
scene.world.node_tree.nodes['Background'].inputs[1].default_value=.5
rb('studio-floor',-200,200,-200,200,-.025,-.012,'graphite',.001,.001)
for name,loc,power,size in [('key',(-2,-3,4),350,3),('fill',(2,-1,2),150,2),('rim',(0,3,3),400,2)]:
    bpy.ops.object.light_add(type='AREA',location=loc);o=bpy.context.object;o.name=name;o.data.energy=power;o.data.shape='DISK';o.data.size=size
    o.rotation_euler=(Vector((0,0,.6))-o.location).to_track_quat('-Z','Y').to_euler()
bpy.ops.object.camera_add();cam=bpy.context.object;scene.camera=cam;cam.data.type='ORTHO';scene.view_settings.view_transform='AgX'
for name,loc,target,scale in [('assembly',(1.2,-3.8,1.65),(0,0,.62),1.47),('front',(0,-4,1.24),(0,0,.61),1.44),('games',(.65,-2,1.2),(-.03,0,.42),.89)]:
    cam.location=loc;cam.rotation_euler=(Vector(target)-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.ortho_scale=scale
    scene.render.filepath=os.path.join(RENDER,name+'.png');bpy.ops.render.render(write_still=True)
bpy.ops.wm.save_as_mainfile(filepath=os.path.join(SRC,'bedroom-tv-v2.blend'))
print('ASSEMBLED',DST,flush=True)
