import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id);
const product=$('product');
const projects=[{title:'Echo Frequency',words:['ECHO','FREQUENCY'],category:'Game design & development',summary:'Not every message tells the truth.',description:'A radio mystery on Blackwater Island. Tune into competing realities, record their signals, and decide what to believe.',contribution:'Game design · Art direction · Development',stack:'Godot · GDScript',status:'In development · v0.17',model:'cab-echo-frequency.glb',marquee:'/assets/media/echo-frequency/marquee.webp',color:'#9cdbd5',shots:['/assets/media/echo-frequency/shots/01-radio-front.webp','/assets/media/echo-frequency/shots/02-signal-found.webp','/assets/media/echo-frequency/shots/04-pinboard.webp','/assets/media/echo-frequency/shots/06-station-room.webp'],captions:['The Blackwater station receiver','An unknown voice at 107.3 MHz','Connecting transmissions on the pinboard','Inside the coastal radio station'],story:'Listen. Cross-check. Write it down. Echo Frequency is built around interpreting information: tune the receiver, compare broadcasts, and find contradictions. The interface is part of the place you inhabit. The project is in development; these are actual screenshots of the current work.'},{title:'Riftback',words:['RIFT','BACK'],category:'Product design & development',summary:'A clearer way into League Classic.',description:'A fan-built reference for League Classic. Champions, builds, items and routes, organised around the way players search.',contribution:'Product strategy · UI · Development',stack:'Next.js · TypeScript',status:'Live · Independent product',model:'mach-riftback.glb',marquee:'/assets/media/riftback/marquee.webp',color:'#cec2a8',shots:['/assets/media/riftback/home.webp','/assets/media/riftback/champion-ahri.webp','/assets/media/riftback/builds.webp','/assets/media/riftback/jungle-routes.webp'],captions:['The starting point for League Classic','Champion detail and build paths','Finding a build by champion and role','Jungle routes, step by step'],story:'One connected reference, from champion to build. Product concept, information structure, content pipeline, UI and development come together in Riftback. Search connects champions, builds, items and routes. The public product contains 63 champions, 105 builds and 149 items.'}];
const initial=new URLSearchParams(location.search);
let selected=initial.get('project')==='riftback'?1:0,shot=0,view=['hall','project','gallery'].includes(initial.get('view'))?initial.get('view'):'hall',direction=initial.get('design')==='contact'?'contact':'afterimage',mobile=initial.get('device')==='mobile';
let trigger=null;
function update(){const p=projects[selected];history.replaceState(null,'',`?design=${direction}&view=${view}&device=${mobile?'mobile':'desktop'}&project=${selected?'riftback':'echo-frequency'}`);product.dataset.view=view;product.dataset.direction=direction;product.classList.toggle('mobile',mobile);product.style.setProperty('--accent',p.color);document.querySelectorAll('[data-view]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',String(b.dataset.view===view));});document.querySelectorAll('button[data-direction]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.direction===direction)));$('device').setAttribute('aria-pressed',String(mobile));$('device').innerHTML=(mobile?'Desktop':'Mobile')+' <span>↗</span>';
$('hall-category').textContent=p.category;$('contact-title').innerHTML=p.title.split(' ').join('<br>');$('contact-image').src=p.shots[0];$('contact-image').alt=p.captions[0];const adjacent=projects[(selected+1)%projects.length];document.querySelector('.adjacent img').src=adjacent.shots[0];document.querySelector('.adjacent img').alt=adjacent.title+' preview';document.querySelector('.adjacent b').textContent=adjacent.title+' ↗';$('project-title').textContent=p.title;$('project-role').textContent=p.category;$('project-description').textContent=p.description;$('project-image').src=p.shots[0];$('project-image').alt=p.captions[0];$('project-caption').textContent=p.captions[0];$('shot-count').textContent='01 / 04';$('contribution').textContent=p.contribution;$('stack').textContent=p.stack;$('status').textContent=p.status;$('gallery-title').textContent=p.title;$('gallery-kind').textContent=p.category;$('gallery-image').src=p.shots[shot];$('gallery-image').alt=p.captions[shot];$('gallery-caption').textContent=p.captions[shot];$('dock-title').textContent=p.title;$('dock-summary').textContent=p.summary;$('dock-eyebrow').textContent=view==='gallery'?'Gallery · '+p.category:view==='project'?'Project overview':'Selected project';$('dock-counter').textContent=view==='gallery'?`${String(shot+1).padStart(2,'0')} / 04`:`${String(selected+1).padStart(2,'0')} / 02`;$('dock-primary').innerHTML=`<span>${view==='hall'?'Explore project':view==='project'?'Open gallery':product.classList.contains('expanded')?'Exit fullscreen':'Fullscreen'}</span><b>${view==='gallery'?'⤢':'↗'}</b>`;document.querySelectorAll('.dock [data-action="previous"]').forEach(b=>b.setAttribute('aria-label',view==='gallery'?'Previous screenshot':'Previous project'));document.querySelectorAll('.dock [data-action="next"]').forEach(b=>b.setAttribute('aria-label',view==='gallery'?'Next screenshot':'Next project'));
$('review-note').textContent=direction==='afterimage'?'A / Architectural typography. Real cabinet. One clear control strip.':'B / Oversized screenshot. Cabinet overlap. An editorial composition.';
closeModal(false);sceneUpdate();}
function choose(i){selected=(i+projects.length)%projects.length;shot=0;update();}
function setView(v){view=v;product.classList.remove('expanded');update();}
function closeModal(restore=true){const was=!$('modal').hidden;$('modal').hidden=true;if(was&&restore)trigger?.focus();}
function modal(kind){trigger=document.activeElement;$('modal').hidden=false;$('modal-eyebrow').textContent=kind==='projects'?'Selected for the design study':'Dennis Bierreth-Fernandez';if(kind==='projects'){$('modal-title').textContent='Choose a project.';$('modal-content').innerHTML=projects.map((p,i)=>`<button class="project-choice" data-project="${i}"><img src="${p.shots[0]}" alt=""><span><b>${p.title}</b><small>${p.category}</small></span></button>`).join('')+'<p style="font-size:12px">Two representative projects are included in this mockup.</p>';}else if(kind==='about'){$('modal-title').textContent='Direction meets making.';$('modal-content').innerHTML='<p>Art director, UX/UI designer, and independent builder of apps and games.</p><p>A portfolio you can walk through, with a direct route to the work whenever you need it.</p>';}else if(kind==='contact'){$('modal-title').textContent='Let’s make something.';$('modal-content').innerHTML='<p>Art direction, digital products, or an idea worth exploring.<br><br><a href="mailto:dennis@dennisbf.design">dennis@dennisbf.design ↗</a></p>';}else{$('modal-title').textContent='The thinking behind it.';$('modal-content').textContent='';const p=document.createElement('p');p.textContent=projects[selected].story;$('modal-content').appendChild(p);}requestAnimationFrame(()=>$('modal').querySelector('.close').focus());}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.project!==undefined){choose(Number(b.dataset.project));return;}if(b.dataset.direction){direction=b.dataset.direction;update();return;}if(b.dataset.view){setView(b.dataset.view);return;}if(b.id==='device'){mobile=!mobile;update();return;}const a=b.dataset.action;if(a==='previous'||a==='next'){if(view==='gallery'){shot=(shot+(a==='next'?1:-1)+projects[selected].shots.length)%projects[selected].shots.length;update();}else choose(selected+(a==='next'?1:-1));}else if(a==='explore'){if(view==='hall')setView('project');else if(view==='project')setView('gallery');else{product.classList.toggle('expanded');update();}}else if(a==='home')setView('hall');else if(a==='project'||a==='gallery')setView(a);else if(a==='close')closeModal();else if(a)modal(a);});
$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal();});document.addEventListener('keydown',e=>{if(!$('modal').hidden){if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const focus=[...$('modal').querySelectorAll('button,a[href]')],first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}if(e.key==='Escape'){if(product.classList.contains('expanded')){product.classList.remove('expanded');update();}else setView(view==='gallery'?'project':'hall');}if(e.target.closest('button,a,input,select'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const delta=e.key==='ArrowRight'?1:-1;if(view==='gallery'){shot=(shot+delta+projects[selected].shots.length)%projects[selected].shots.length;update();}else choose(selected+delta);}});
// A separate, small presentation scene. Existing website rendering is untouched.
const holder=$('scene');let renderer,scene,camera,main,wall,floor,titlePlanes=[],tv,models=[],frame=0,raf=0;let last=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const target={x:0,y:0,z:0,rotation:-.13};const loader=new GLTFLoader(),textures=new THREE.TextureLoader();
function requestRender(){if(!renderer)return;frame=performance.now();if(!raf){last=performance.now();raf=requestAnimationFrame(tick);}}
function tick(now){raf=0;const dt=Math.min(.05,(now-last)/1000);last=now;const k=reduced?1:Math.min(1,dt*16);if(main){main.position.x+=(target.x-main.position.x)*k;main.position.y+=(target.y-main.position.y)*k;main.position.z+=(target.z-main.position.z)*k;main.rotation.y+=(target.rotation-main.rotation.y)*k;}renderer.render(scene,camera);if(now-frame<400&&!reduced)raf=requestAnimationFrame(tick);}
function textPlane(text,width,height,y){const c=document.createElement('canvas');c.width=2400;c.height=420;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#8595a8';ctx.font='350 340px Outfit';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,1200,205,2350);const map=new THREE.CanvasTexture(c);map.colorSpace=THREE.SRGBColorSpace;map.anisotropy=renderer.capabilities.getMaxAnisotropy();const mat=new THREE.MeshBasicMaterial({map,transparent:true,opacity:.35,depthWrite:false,toneMapped:false});const p=new THREE.Mesh(new THREE.PlaneGeometry(width,height),mat);p.position.set(0,y,-1.18);scene.add(p);titlePlanes.push(p);}
function makeTitles(){if(!scene)return;for(const p of titlePlanes){scene.remove(p);p.geometry.dispose();p.material.map.dispose();p.material.dispose();}titlePlanes=[];const words=projects[selected].words;textPlane(words[0],mobile?5.6:9,1.55,mobile?2.35:2.25);textPlane(words[1],mobile?5.4:10.9,mobile?.95:1.90,mobile?1.25:.86);for(const t of titlePlanes)t.visible=direction==='afterimage'&&view==='hall';requestRender();}
function imageTexture(src,cb){const image=new Image();image.onload=()=>{const c=document.createElement('canvas');c.width=1024;c.height=768;const ctx=c.getContext('2d');ctx.fillStyle='#03080c';ctx.fillRect(0,0,c.width,c.height);const s=Math.min(c.width/image.width,c.height/image.height);ctx.drawImage(image,(c.width-image.width*s)/2,(c.height-image.height*s)/2,image.width*s,image.height*s);const t=new THREE.CanvasTexture(c);t.flipY=false;t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;cb(t);requestRender();};image.src=src;}
function loadModel(p,i){return new Promise(resolve=>{loader.load('/assets/models/'+p.model,g=>{const root=g.scene;root.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const n=o.name.toLowerCase();const mat=o.material;if(n==='glass'){o.visible=false;return;}if(n==='screen'){o.material=new THREE.MeshBasicMaterial({color:0xffffff,toneMapped:false});imageTexture(p.shots[0],t=>{o.material.map=t;o.material.needsUpdate=true;});}else if(n==='marquee'){const c=document.createElement('canvas');c.width=2048;c.height=380;const ctx=c.getContext('2d');ctx.fillStyle='#060b10';ctx.fillRect(0,0,2048,380);ctx.fillStyle=p.color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='600 205px Outfit';ctx.fillText(p.title.toUpperCase(),1024,190,1850);const t=new THREE.CanvasTexture(c);t.flipY=false;t.colorSpace=THREE.SRGBColorSpace;o.material=new THREE.MeshBasicMaterial({map:t,toneMapped:false});requestRender();}else if(mat){mat.roughness=Math.max(mat.roughness??.5,.42);if(mat.emissiveIntensity)mat.emissiveIntensity=Math.min(mat.emissiveIntensity,.65);}});const box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),s=2.65/size.y;root.scale.setScalar(s);root.position.set(-center.x*s,-box.min.y*s,-center.z*s);const group=new THREE.Group();group.add(root);group.visible=i===selected;main.add(group);models[i]=group;requestRender();resolve();},undefined,()=>resolve());});}
function sceneUpdate(){if(!scene)return;for(let i=0;i<models.length;i++)if(models[i])models[i].visible=i===selected;const contact=direction==='contact'&&view==='hall';renderer.setClearColor(0x080b10,contact?0:1);wall.visible=!contact;floor.visible=!contact&&view==='hall';tv.visible=!contact&&view==='hall'&&!mobile;if(tv.userData.project!==selected){const i=selected;tv.userData.project=i;imageTexture(projects[i].shots[0],t=>{if(tv.userData.project!==i){t.dispose();return;}tv.children[1].material.map?.dispose();tv.children[1].material.map=t;tv.children[1].material.needsUpdate=true;});}main.scale.setScalar(view==='project'?.55:contact?(mobile?.65:.70):1);target.x=view==='project'?(mobile?-1.1:-2.55):contact?(mobile?-.65:-2.2):mobile?.2:.35;target.y=view==='project'?1.40:contact?.25:0;target.z=contact?1:0;target.rotation=view==='project'?.23:contact?.34:-.11;const w=holder.clientWidth,h=holder.clientHeight;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(0,mobile?1.80:1.9,mobile?8.6:7.4);camera.lookAt(0,mobile?1.40:1.22,0);camera.updateProjectionMatrix();makeTitles();requestRender();}
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;holder.appendChild(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(34,1,.1,40);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.05).texture;scene.environmentIntensity=.38;pmrem.dispose();scene.add(new THREE.HemisphereLight(0xc5d5f1,0x111820,1.1));const key=new THREE.SpotLight(0xc6d9ed,48,18,.8,.8,1.4);key.position.set(-3.5,6,4);key.target.position.set(0,1,0);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.bias=-.0002;scene.add(key,key.target);const edge=new THREE.PointLight(0xa1cacb,7,10);edge.position.set(2.5,3,-.2);scene.add(edge);const soft=new THREE.PointLight(0x8497b6,12,10);soft.position.set(-3,2,1);scene.add(soft);wall=new THREE.Mesh(new THREE.PlaneGeometry(30,12),new THREE.MeshStandardMaterial({color:0x0b1019,roughness:1,metalness:0}));wall.position.set(0,4,-1.3);scene.add(wall);floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x0d121b,roughness:.42,metalness:.35}));floor.rotation.x=-Math.PI/2;floor.position.y=-.012;floor.receiveShadow=true;scene.add(floor);main=new THREE.Group();scene.add(main);tv=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.24,.76,.07),new THREE.MeshStandardMaterial({color:0x181d26,roughness:.7,metalness:.35}));tv.add(body);const screen=new THREE.Mesh(new THREE.PlaneGeometry(1.14,.65),new THREE.MeshBasicMaterial({color:0x7c8e9e,toneMapped:false}));screen.position.z=.041;tv.add(screen);for(const x of [-.38,.38]){const stem=new THREE.Mesh(new THREE.BoxGeometry(.022,.7,.022),new THREE.MeshStandardMaterial({color:0x454d58,metalness:.65,roughness:.6}));stem.position.set(x,.7,-.03);tv.add(stem);}tv.position.set(2.75,2.68,-.74);scene.add(tv);Promise.all(projects.map(loadModel)).then(sceneUpdate);new ResizeObserver(sceneUpdate).observe(holder);document.fonts.ready.then(makeTitles);}catch(e){holder.innerHTML='<p style="position:absolute;top:45%;left:30%;color:#b5c4d5">3D preview unavailable. Project and gallery mockups are still available.</p>';console.error(e);}
update();

const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
function overCabinet(e){if(!renderer||!main||view==='gallery'||!$('modal').hidden||e.target.closest('button,a'))return false;const r=holder.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObject(models[selected]??main,true).some(h=>h.object.visible);}
product.addEventListener('pointermove',e=>{product.style.cursor=overCabinet(e)?'pointer':'';});
product.addEventListener('click',e=>{if(overCabinet(e))setView(view==='hall'?'project':'gallery');});
