import {chromium,firefox} from 'playwright';
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.QA_BASE_URL||'http://localhost:4321/';
const out=process.env.QA_OUT||'.source-assets/blue/qa/play';await fs.mkdir(out,{recursive:true});const results=[];
for(const [engine,width,reduce] of [['chromium',1440,false],['firefox',1440,false],['chromium',390,false],['chromium',1440,true]]){
 const browser=await({chromium,firefox}[engine]).launch({headless:true,...(engine==='chromium'?{args:['--use-angle=d3d11']}: {})});
 try{const p=await browser.newPage({viewport:{width,height:900},hasTouch:width<600,reducedMotion:reduce?'reduce':'no-preference'});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await p.goto(base,{timeout:120000});await p.waitForFunction(()=>window.__hall?.readyDone&&window.__hall.blue?.toys?.toys.length===2,null,{timeout:120000});await p.waitForTimeout(8000);
 await p.evaluate(()=>{const h=window.__hall,b=h.blue;h.stop();b.toy=null;b.enter('idle');b.inBed=false;b.elevation=0;b.ground=0;b.undisturbed=false;b.body.position.set(-.95,0,.88);b.body.rotation.y=Math.PI;b.goal.copy(b.body.position);for(let i=0;i<120;i++)b.update(1/60,h.camera,true,false);const ball=b.toys.toys.find(t=>t.ball),mouse=b.toys.toys.find(t=>!t.ball);ball.position.set(-.95,.055,.57);ball.velocity.set(0,0,0);mouse.position.set(-.4,.06,.5);mouse.velocity.set(0,0,0);b.update(0,h.camera,true,false);h.dirty=h.mirrorDirty=true;h.renderFrame();});
 const session=width<600?await p.context().newCDPSession(p):null;
 const update=()=>p.evaluate(reduce=>{const h=window.__hall;h.blue.update(0,h.camera,true,reduce);h.dirty=h.mirrorDirty=true;h.renderFrame();},reduce);
 await update();
 const drag=async(dx,dy,cancel=false)=>{const box=await p.getByRole('button',{name:'Ball anstupsen',exact:true}).boundingBox();assert.ok(box);const x=box.x+box.width/2,y=box.y+box.height/2;
 if(session)await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});else {await p.mouse.move(x,y);await p.mouse.down();}
 for(let i=1;i<=8;i++){const point={x:x+dx*i/8,y:y+dy*i/8};if(session)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[point]});else await p.mouse.move(point.x,point.y);await p.waitForTimeout(16);await update();}
 const held=await p.evaluate(()=>{const t=window.__hall.blue.toys.toys.find(t=>t.ball);return{held:t.held,p:t.position.toArray()};});assert.equal(held.held,true);if(!reduce)assert.ok(held.p[1]>.25);
 if(cancel){if(session)await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});else {await p.evaluate(()=>{const d=window.__hall.blue.toys.drag;d.toy.button.dispatchEvent(new PointerEvent('pointercancel',{pointerId:d.id,bubbles:true}));});await p.mouse.up();}}else if(session)await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});else await p.mouse.up();
 const released=await p.evaluate(()=>{const t=window.__hall.blue.toys.toys.find(t=>t.ball);return{held:t.held,p:t.position.toArray(),v:t.velocity.toArray()};});assert.equal(released.held,false);return {held,released};};
 const high=await drag(0,width<600?-65:-100);
 const run=await p.evaluate(reduce=>{const h=window.__hall,b=h.blue;const moods=new Set(),clips=new Set();let maxHeight=0,maxStep=0,maxDetail=null,last=b.body.position.clone(),bad=0;const start=b.toyContacts;for(let i=0;i<60*16;i++){b.update(1/60,h.camera,true,reduce);moods.add(b.mood);if(b.mood==='playjump')clips.add(b.playClip);maxHeight=Math.max(maxHeight,b.body.position.y);if(last.distanceTo(b.body.position)>maxStep){maxStep=last.distanceTo(b.body.position);maxDetail={i,mood:b.mood,age:b.age,from:last.toArray(),to:b.body.position.toArray(),playFrom:b.playFrom.toArray(),playTo:b.playTo.toArray()};}last.copy(b.body.position);for(const t of b.toys.toys)if(!t.position.toArray().every(Number.isFinite)||t.position.y<t.radius-.001)bad++;}h.dirty=h.mirrorDirty=true;h.renderFrame();return{moods:[...moods],clips:[...clips],maxHeight,maxStep,maxDetail,bad,contacts:b.toyContacts-start,catches:b.toyCatches};},reduce);
 assert.equal(run.bad,0);assert.ok(run.maxStep<.09);if(!reduce){assert.ok(run.clips.includes('catch'),'reachable high throw triggers a catch attempt');assert.ok(run.contacts>0,'Blue reaches a toy with a paw');}else assert.equal(run.maxHeight,0);
 await p.screenshot({path:out+'/'+engine+'-'+width+'-'+reduce+'.png'});
 // A flat, distant release must be chased on the floor, not teleported to.
 const far=await p.evaluate(reduce=>{const h=window.__hall,b=h.blue,t=b.toys.toys.find(t=>t.ball);b.toy=null;b.enter('idle');b.body.position.set(-1.8,0,.75);b.body.rotation.y=Math.PI/2;b.elevation=0;b.inBed=false;t.position.set(innerWidth<600?-.35:.65,.055,.65);t.velocity.set(.35,0,0);b.toy=reduce?null:t;b.playUntil=b.clock+28;let maxSpeed=0,jumps=0;const start=b.body.position.clone();for(let i=0;i<360;i++){b.update(1/60,h.camera,true,reduce);maxSpeed=Math.max(maxSpeed,b.speed);if(b.mood==='playjump')jumps++;}return{maxSpeed,jumps,moved:b.body.position.distanceTo(start)};},reduce);
 await p.evaluate(()=>{const h=window.__hall,t=h.blue.toys.toys.find(t=>t.ball);t.position.set(-.95,.055,.57);t.velocity.set(0,0,0);h.blue.toys.toys.find(t=>!t.ball).position.set(-.4,.06,.5);});await update();const cancelled=await drag(0,-80,true);assert.deepEqual(cancelled.released.v,[0,0,0]);if(!reduce){assert.ok(far.maxSpeed>.6);assert.ok(far.moved>.6);}assert.deepEqual(errors,[]);assert.equal(new URL(p.url()).pathname,'/');results.push({engine,width,reduce,high,run,far,errors});console.log(JSON.stringify(results.at(-1)));await p.close();
 }finally{await browser.close()}
}
await fs.writeFile(out+'/report.json',JSON.stringify(results,null,2));
