import{chromium}from'playwright';import assert from'node:assert/strict';import fs from'node:fs/promises';
import {base as baseUrl,outDir} from './_env.mjs';
const BASE=baseUrl('http://localhost:4322');
const out=outDir('smoothness-2026-09-11');
const base=(process.env.QA_BASE||BASE).replace(/\/+$/,'');const browser=await chromium.launch({headless:true,args:['--use-angle=d3d11']});const all=[];
try{for(const width of [1366,390]){const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[],assetRequests=[],csp=[];await page.exposeFunction('qaCsp',e=>csp.push(e));await page.addInitScript(()=>document.addEventListener('securitypolicyviolation',e=>window.qaCsp({directive:e.effectiveDirective,blocked:e.blockedURI})));page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\.glb|hall-environment/.test(r.url()))assetRequests.push(r.url());});
await page.goto(base+'/');await page.waitForFunction(()=>document.querySelector('.hall.is-3d')&&!document.documentElement.classList.contains('gl-pending'),null,{timeout:60000});await page.evaluate(()=>{window.__qaCanvas=document.querySelector('.hall__canvas');window.__qaVisit=Math.random();});const visit=await page.evaluate(()=>window.__qaVisit),initialAssets=assetRequests.length;
const hops=[];for(const path of ['/impressum/','/about/','/privacy/','/contact/','/work/','/work/nexus/','/nexus/','/work/nexus/','/work/lowlight/','/lowlight/','/nexus/','/lowlight/','/about/','/en/impressum/','/en/about/','/']){
await page.evaluate(path=>{const a=document.createElement('a');a.href=path;document.body.appendChild(a);a.click();a.remove();},path);await page.waitForURL(base+path);await page.waitForTimeout(200);
const state=await page.evaluate(()=>({same:window.__qaCanvas===document.querySelector('.hall__canvas'),visit:window.__qaVisit,parked:!!document.querySelector('[data-hall-parked]'),pending:document.documentElement.classList.contains('gl-pending'),loaderVisible:[...document.querySelectorAll('.hall-startup')].some(e=>getComputedStyle(e).visibility!=='hidden'&&Number(getComputedStyle(e).opacity)>0),canvases:document.querySelectorAll('.hall__canvas').length,overflow:document.documentElement.scrollWidth>innerWidth}));assert.equal(state.same,true,path+' canvas replaced');assert.equal(state.visit,visit,path+' document reloaded');assert.equal(state.pending,false,path+' restarted loading');assert.equal(state.loaderVisible,false,path+' loader replayed');assert.equal(state.canvases,1);assert.equal(state.overflow,false,path+' overflow');
if(path==='/nexus/'){await page.locator('#tab-library').focus();await page.keyboard.press('End');assert.equal(await page.locator('#tab-couch').getAttribute('aria-selected'),'true');}
if(path==='/lowlight/'){await page.locator('[data-record="starboy"]').click();await page.waitForFunction(()=>document.querySelector('#record-stage')?.dataset.active==='starboy');}
hops.push({path,...state});}
await page.goBack();await page.waitForURL(base+'/en/about/');assert.equal(await page.evaluate(()=>window.__qaCanvas===document.querySelector('.hall__canvas')),true);await page.goForward();await page.waitForURL(base+'/');assert.equal(await page.evaluate(()=>window.__qaCanvas===document.querySelector('.hall__canvas')),true);assert.equal(assetRequests.length,initialAssets,'3D assets re-requested');assert.deepEqual(errors,[]);assert.deepEqual(csp,[]);all.push({width,ok:true,initialAssets,hops,errors});console.log(JSON.stringify({width,ok:true,hops:hops.length,initialAssets}));await page.close();}}finally{await browser.close();}await fs.writeFile(out+'/session-navigation.json',JSON.stringify(all,null,2));